"""initial tables

Revision ID: 0102a1c559c2
Revises: 
Create Date: 2026-06-27 18:28:27.966092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0102a1c559c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lan_ip', sa.String(length=45), nullable=False),
    sa.Column('wg_ip', sa.String(length=45), nullable=True),
    sa.Column('wg_public_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'PROVISIONING', name='nodestatus', native_enum=False, length=20), nullable=False),
    sa.Column('hardware', sa.Text(), nullable=True),
    sa.Column('macos_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.Enum('MONTHLY', 'ANNUAL', 'DAILY', 'HOURLY', name='plantype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PROVISIONING', 'DEPROVISIONING', name='clientstatus', native_enum=False, length=20), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(length=50), nullable=True),
    sa.Column('wg_private_key', sa.String(length=64), nullable=True),
    sa.Column('wg_ip', sa.String(length=45), nullable=True),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_node_id'), 'clients', ['node_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_client_id'), 'assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_assignments_node_id'), 'assignments', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_node_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_client_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_clients_node_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
